title: Perspectives on Scientific Error
description: Annual workshop on statistical, philosophical, and meta-scientific issues of scientific error.
url: "https://pse-workshop.github.io"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from

aux_links:
  "Join Mailing List":
    - "https://forms.office.com/Pages/ResponsePage.aspx?id=zcrxoIxhA0S5RXb7PWh05aZxUG5f7nZHklQvxNAfLhpUQkZJNDRBMllTTE02QUxWSTRaN1BIQUE2NC4u"

aux_links_new_tab: true

search_enabled: false

footer_content: "Perspectives on Scientific Error Workshop Series"
